"""Schemas for explanation generation results."""

from typing import Any

from pydantic import BaseModel, Field


class ExplanationResult(BaseModel):
    """Explanation generated by LLM."""

    summary: str | None = None
    strengths: list[str] = Field(default_factory=list, max_length=3)
    concerns: list[str] = Field(default_factory=list, max_length=3)
    unknowns: list[str] = Field(default_factory=list, max_length=5)
    must_gaps: list[str] = Field(default_factory=list)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExplanationResult":
        """Create from raw dictionary (LLM output)."""
        return cls(
            summary=data.get("summary"),
            strengths=data.get("strengths", [])[:3],
            concerns=data.get("concerns", [])[:3],
            unknowns=data.get("unknowns", [])[:5],
            must_gaps=data.get("must_gaps", []),
        )
